# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApzAyBlctoquLq-M90ahbBokTXTZPCli
"""

import streamlit as st
import pandas as pd
import os
import qrcode

DATA_FILE = "data.csv"
QR_DIR = "qrcodes"

os.makedirs(QR_DIR, exist_ok=True)

def generate_user_id():
    if not os.path.exists(DATA_FILE):
        return "USR0001"
    df = pd.read_csv(DATA_FILE)
    return f"USR{len(df)+1:04d}"

def save_data(data):
    df_new = pd.DataFrame([data])
    header = not os.path.exists(DATA_FILE)
    df_new.to_csv(DATA_FILE, mode="a", header=header, index=False)

def generate_qr(user_id):
    base_url = st.secrets["BASE_URL"]
    url = f"{base_url}/?uid={user_id}"
    img = qrcode.make(url)
    path = f"{QR_DIR}/{user_id}.png"
    img.save(path)
    return path

def get_user(uid):
    if not os.path.exists(DATA_FILE):
        return None
    df = pd.read_csv(DATA_FILE)
    row = df[df["User_ID"] == uid]
    return row.iloc[0] if not row.empty else None

query = st.query_params
if "uid" in query:
    uid = query["uid"]
    data = get_user(uid)

    st.title("📄 Detail Data Pengguna")
    if data is not None:
        st.json(data.to_dict())
        st.image(f"{QR_DIR}/{uid}.png")
    else:
        st.error("Data tidak ditemukan")
    st.stop()

st.title("🤖 Rule-Based Chatbot Input Data")

user_id = generate_user_id()
st.info(f"User_ID otomatis: {user_id}")

with st.form("form_input"):
    nama = st.text_input("Nama")
    usia = st.number_input("Usia", 0, 120)
    pekerjaan = st.text_input("Pekerjaan")
    submit = st.form_submit_button("Simpan Data")

if submit:
    data = {
        "User_ID": user_id,
        "Nama": nama,
        "Usia": usia,
        "Pekerjaan": pekerjaan
    }

    save_data(data)
    qr_path = generate_qr(user_id)

    st.success("✅ Data berhasil disimpan")
    st.image(qr_path)
    st.write("📱 Scan QR untuk melihat detail data")

    if st.button("➕ Tambah Data Lagi"):
        st.experimental_rerun()